[package]
name = "bottlerocket-bootstrap-associate-eip"
version = "0.2.1"
edition = "2021"

[dependencies]
aws-config = "0.55.0"
aws-credential-types = "0.55.0"
aws-sdk-ec2 = "0.25.1"
env_logger = "0.10.0"
http = "0.2.9"
rand = "0.8.5"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
tokio = { version = "1.27.0", features = ["macros"] }

[dev-dependencies]
chrono = "0.4.24"
const-str = "0.5.4"
futures = "0.3.28"
hyper = { version = "0.14.25", features = ["server"] }
serde_urlencoded = "0.7.1"
tempfile = "3.5.0"
tokio = { version = "1.27.0", features = ["rt-multi-thread"] }

[profile.release]
strip = true

[profile.release-build]
inherits = "release"
opt-level = "z"
strip = true
debug = false
lto = true
codegen-units = 1

[profile.debug-build]
inherits = "release"
opt-level = "z"
strip = false
debug = true
lto = true
codegen-units = 1
