[package]
name = "bottlerocket-bootstrap-associate-eip"
version = "0.2.1"
edition = "2021"

[dependencies]
aws-config = "0.53.0"
aws-credential-types = "0.53.0"
aws-sdk-ec2 = "0.23.0"
env_logger = "0.10.0"
http = "0.2.8"
rand = "0.8.5"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.24.1", features = ["macros"] }

[dev-dependencies]
chrono = "0.4.23"
const-str = "0.5.3"
futures = "0.3.25"
hyper = { version = "0.14.23", features = ["server"] }
serde_urlencoded = "0.7.1"
tempfile = "3.3.0"
tokio = { version = "1.24.1", features = ["rt-multi-thread"] }

[profile.release-build]
inherits = "release"
opt-level = "s"
strip = true
debug = false

[profile.debug-build]
inherits = "release"
opt-level = "s"
strip = false
debug = true
