[package]
name = "bottlerocket-bootstrap-associate-eip"
version = "0.2.1"
edition = "2021"

[dependencies]
aws-config = "0.54.1"
aws-credential-types = "0.54.1"
aws-sdk-ec2 = "0.24.0"
env_logger = "0.10.0"
http = "0.2.8"
rand = "0.8.5"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tokio = { version = "1.25.0", features = ["macros"] }

[dev-dependencies]
chrono = "0.4.23"
const-str = "0.5.3"
futures = "0.3.26"
hyper = { version = "0.14.24", features = ["server"] }
serde_urlencoded = "0.7.1"
tempfile = "3.3.0"
tokio = { version = "1.25.0", features = ["rt-multi-thread"] }

[profile.release]
strip = true

[profile.release-build]
inherits = "release"
opt-level = "z"
strip = true
debug = false
lto = true
codegen-units = 1

[profile.debug-build]
inherits = "release"
opt-level = "z"
strip = false
debug = true
lto = true
codegen-units = 1
