[package]
name = "bottlerocket-bootstrap-associate-eip"
version = "0.2.2"
edition = "2021"

[dependencies]
aws-config = "1.1.2"
aws-credential-types = "1.1.2"
aws-sdk-ec2 = "1.14.0"
env_logger = "0.10.1"
http = "1.0.0"
rand = "0.8.5"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
tokio = { version = "1.35.1", features = ["macros"] }

[dev-dependencies]
chrono = "0.4.31"
const-str = "0.5.6"
futures = "0.3.30"
hyper = { version = "1.1.0", features = ["server"] }
serde_urlencoded = "0.7.1"
tempfile = "3.9.0"
tokio = { version = "1.35.1", features = ["rt-multi-thread"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }

[profile.release]
strip = true

[profile.release-build]
inherits = "release"
opt-level = "z"
strip = true
debug = false
lto = true
codegen-units = 1

[profile.debug-build]
inherits = "release"
opt-level = "z"
strip = false
debug = true
lto = true
codegen-units = 1
