[package]
name = "bottlerocket-bootstrap-associate-eip"
version = "0.2.0"
edition = "2021"

[dependencies]
aws-config = "0.49.0"
aws-sdk-ec2 = "0.19.0"
env_logger = "0.9.1"
http = "0.2.8"
rand = "0.8.5"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
tokio = { version = "1", features = ["macros"] }

[dev-dependencies]
chrono = "0.4.22"
const-str = "0.5.1"
futures = "0.3.24"
hyper = { version = "0.14.20", features = ["server"] }
serde_urlencoded = "0.7.1"
tempfile = "3.3.0"
tokio = { version = "1", features = ["rt-multi-thread"] }
